services:

  mysql:
    image: mysql:8.0
    container_name: auth-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend

    container_name: auth-backend

    depends_on:
      - mysql

    env_file:
      - "C:/Users/aryan/OneDrive/Desktop/ProjectsEnv/AuthApp/AuthAppBackend.env"

    ports:
      - "8083:8083"

volumes:
  mysql-data: